version: '3'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scraping_recettes_development
    volumes:
      - ./data:/var/lib/postgresql/data
