---
engine_version: 0.4.17
file_version: 2023-06-12 02:08:13.756854000 Z
resources:
- name: ingredient
  preferences:
    columns:
    - column_type: link
      name: cover
  updated_at: 2023-06-03 05:02:35.028195000 +00:00
- name: recipe
  preferences:
    columns:
    - column_type: richtext
      name: instruction
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: updated_at
    - column_type: link
      name: cover
    - column_type: richtext
      name: description
  updated_at: 2023-06-12 02:08:13.756854000 +00:00
- name: recipe_ingredient
  preferences:
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
  updated_at: 2023-06-03 04:59:31.544767000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2023-06-12 01:35:50.537438000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2023-06-12 01:35:50.668535000 +00:00
